/* ============================================
   PDF Export Utility
   Uses html2pdf.js to capture DOM elements as PDF
   ============================================ */

/**
 * Export a DOM element as a downloadable PDF file
 * @param {HTMLElement} element - The DOM element to capture
 * @param {string} filename - Output filename (without .pdf extension)
 * @param {object} options - Optional overrides
 * @returns {Promise<void>}
 */
export async function exportToPdf(element, filename = 'scroll-io-summary', options = {}) {
  if (!element) {
    throw new Error('No element provided for PDF export');
  }

  // Dynamically import html2pdf.js (it's large, so lazy-load)
  const html2pdf = (await import('html2pdf.js')).default;

  const defaultOptions = {
    margin:       0.5,
    filename:     `${filename}.pdf`,
    image:        { type: 'jpeg', quality: 0.95 },
    html2canvas:  {
      scale:       2,           // Retina-quality screenshots
      useCORS:     true,
      letterRendering: true,
      logging:     false,
      backgroundColor: '#FFFFFF',
    },
    jsPDF:        {
      unit:        'in',
      format:      'letter',
      orientation: 'portrait',
    },
    pagebreak:    { mode: ['avoid-all', 'css', 'legacy'] },
  };

  const config = { ...defaultOptions, ...options };
  // Merge nested objects
  config.html2canvas = { ...defaultOptions.html2canvas, ...options.html2canvas };
  config.jsPDF = { ...defaultOptions.jsPDF, ...options.jsPDF };

  await html2pdf().set(config).from(element).save();
}

/**
 * Export a text string as a simple PDF using an embedded print-ready document.
 * Fallback when no DOM element is available.
 * @param {string} title - Document title
 * @param {string} content - Plain text content
 * @param {string} filename - Output filename
 */
export async function exportTextAsPdf(title, content, filename = 'scroll-io-summary') {
  // Create a temporary DOM element with clean styling
  const wrapper = document.createElement('div');
  wrapper.style.cssText = `
    font-family: 'DM Sans', system-ui, sans-serif;
    max-width: 7in;
    margin: 0 auto;
    padding: 40px;
    color: #1A1A2E;
    background: #FFFFFF;
  `;

  wrapper.innerHTML = `
    <h1 style="font-family: 'Space Grotesk', sans-serif; font-size: 28px; font-weight: 700; margin-bottom: 8px; color: #1A1A2E;">
      ${title}
    </h1>
    <hr style="border: none; border-top: 2px solid #6C63FF; margin: 16px 0 24px;" />
    <pre style="font-family: 'DM Sans', system-ui, sans-serif; font-size: 13px; line-height: 1.7; white-space: pre-wrap; color: #333; margin: 0;">
${content}
    </pre>
    <hr style="border: none; border-top: 1px solid #E2E4EA; margin: 32px 0 16px;" />
    <p style="font-size: 10px; color: #999; text-align: center;">
      Generated by Scroll.io · AI-Powered Document Summarizer
    </p>
  `;

  // Temporarily append, render, remove
  document.body.appendChild(wrapper);
  try {
    await exportToPdf(wrapper, filename);
  } finally {
    document.body.removeChild(wrapper);
  }
}
